const response = {
  location: {
    name: "Cairo",
    region: "Al Qahirah",
    country: "Egypt",
    lat: 30.05,
    lon: 31.25,
    tz_id: "Africa/Cairo",
    localtime_epoch: 1645648499,
    localtime: "2022-02-23 22:34",
  },
  current: {
    last_updated_epoch: 1645648200,
    last_updated: "2022-02-23 22:30",
    temp_c: 15.0,
    temp_f: 59.0,
    is_day: 0,
    condition: {
      text: "Partly cloudy",
      icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
      code: 1003,
    },
    wind_mph: 13.6,
    wind_kph: 22.0,
    wind_degree: 280,
    wind_dir: "W",
    pressure_mb: 1012.0,
    pressure_in: 29.88,
    precip_mm: 0.0,
    precip_in: 0.0,
    humidity: 72,
    cloud: 50,
    feelslike_c: 13.2,
    feelslike_f: 55.8,
    vis_km: 10.0,
    vis_miles: 6.0,
    uv: 1.0,
    gust_mph: 20.1,
    gust_kph: 32.4,
  },
  forecast: {
    forecastday: [
      {
        date: "2022-02-23",
        date_epoch: 1645574400,
        day: {
          maxtemp_c: 26.6,
          mintemp_c: 14.8,
          avgtemp_c: 19.8,
          maxwind_kph: 37.4,
          totalprecip_mm: 0.0,
          avgvis_km: 10.0,
          avghumidity: 33.0,
          daily_chance_of_rain: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Sunny",
            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
            code: 1000,
          },
        },
        astro: {
          sunrise: "06:28 AM",
          sunset: "05:50 PM",
          moonrise: "No moonrise",
          moonset: "10:33 AM",
          moon_phase: "Last Quarter",
          moon_illumination: "40",
        },
        hour: [
          {
            time_epoch: 1645567200,
            time: "2022-02-23 00:00",
            temp_c: 18.0,
            temp_f: 64.4,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 4.9,
            wind_kph: 7.9,
            wind_degree: 165,
            wind_dir: "SSE",
            pressure_mb: 1013.0,
            pressure_in: 29.9,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 30,
            cloud: 4,
            feelslike_c: 18.0,
            feelslike_f: 64.4,
            windchill_c: 18.0,
            windchill_f: 64.4,
            heatindex_c: 18.0,
            heatindex_f: 64.4,
            dewpoint_c: 0.0,
            dewpoint_f: 32.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 10.3,
            gust_kph: 16.6,
            uv: 1.0,
          },
          {
            time_epoch: 1645570800,
            time: "2022-02-23 01:00",
            temp_c: 17.4,
            temp_f: 63.3,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 178,
            wind_dir: "S",
            pressure_mb: 1012.0,
            pressure_in: 29.9,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 31,
            cloud: 3,
            feelslike_c: 17.4,
            feelslike_f: 63.3,
            windchill_c: 17.4,
            windchill_f: 63.3,
            heatindex_c: 17.4,
            heatindex_f: 63.3,
            dewpoint_c: -0.1,
            dewpoint_f: 31.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 8.9,
            gust_kph: 14.4,
            uv: 1.0,
          },
          {
            time_epoch: 1645574400,
            time: "2022-02-23 02:00",
            temp_c: 17.1,
            temp_f: 62.8,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 182,
            wind_dir: "S",
            pressure_mb: 1012.0,
            pressure_in: 29.89,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 31,
            cloud: 3,
            feelslike_c: 17.1,
            feelslike_f: 62.8,
            windchill_c: 17.1,
            windchill_f: 62.8,
            heatindex_c: 17.1,
            heatindex_f: 62.8,
            dewpoint_c: -0.1,
            dewpoint_f: 31.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 8.9,
            gust_kph: 14.4,
            uv: 1.0,
          },
          {
            time_epoch: 1645578000,
            time: "2022-02-23 03:00",
            temp_c: 16.6,
            temp_f: 61.9,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 198,
            wind_dir: "SSW",
            pressure_mb: 1012.0,
            pressure_in: 29.88,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 32,
            cloud: 3,
            feelslike_c: 16.6,
            feelslike_f: 61.9,
            windchill_c: 16.6,
            windchill_f: 61.9,
            heatindex_c: 16.6,
            heatindex_f: 61.9,
            dewpoint_c: -0.2,
            dewpoint_f: 31.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 8.1,
            gust_kph: 13.0,
            uv: 1.0,
          },
          {
            time_epoch: 1645581600,
            time: "2022-02-23 04:00",
            temp_c: 16.4,
            temp_f: 61.5,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 4.5,
            wind_kph: 7.2,
            wind_degree: 161,
            wind_dir: "SSE",
            pressure_mb: 1012.0,
            pressure_in: 29.87,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 32,
            cloud: 4,
            feelslike_c: 16.4,
            feelslike_f: 61.5,
            windchill_c: 16.4,
            windchill_f: 61.5,
            heatindex_c: 16.4,
            heatindex_f: 61.5,
            dewpoint_c: -0.2,
            dewpoint_f: 31.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 9.4,
            gust_kph: 15.1,
            uv: 1.0,
          },
          {
            time_epoch: 1645585200,
            time: "2022-02-23 05:00",
            temp_c: 16.1,
            temp_f: 61.0,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 4.7,
            wind_kph: 7.6,
            wind_degree: 165,
            wind_dir: "SSE",
            pressure_mb: 1012.0,
            pressure_in: 29.88,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 33,
            cloud: 4,
            feelslike_c: 16.1,
            feelslike_f: 61.0,
            windchill_c: 16.1,
            windchill_f: 61.0,
            heatindex_c: 16.1,
            heatindex_f: 61.0,
            dewpoint_c: -0.2,
            dewpoint_f: 31.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 9.8,
            gust_kph: 15.8,
            uv: 1.0,
          },
          {
            time_epoch: 1645588800,
            time: "2022-02-23 06:00",
            temp_c: 16.0,
            temp_f: 60.8,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 6.5,
            wind_kph: 10.4,
            wind_degree: 151,
            wind_dir: "SSE",
            pressure_mb: 1012.0,
            pressure_in: 29.87,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 33,
            cloud: 3,
            feelslike_c: 16.0,
            feelslike_f: 60.8,
            windchill_c: 16.0,
            windchill_f: 60.8,
            heatindex_c: 16.0,
            heatindex_f: 60.8,
            dewpoint_c: -0.2,
            dewpoint_f: 31.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 13.6,
            gust_kph: 22.0,
            uv: 1.0,
          },
          {
            time_epoch: 1645592400,
            time: "2022-02-23 07:00",
            temp_c: 15.9,
            temp_f: 60.6,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 5.6,
            wind_kph: 9.0,
            wind_degree: 166,
            wind_dir: "SSE",
            pressure_mb: 1012.0,
            pressure_in: 29.88,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 34,
            cloud: 5,
            feelslike_c: 15.9,
            feelslike_f: 60.6,
            windchill_c: 15.9,
            windchill_f: 60.6,
            heatindex_c: 15.9,
            heatindex_f: 60.6,
            dewpoint_c: 0.0,
            dewpoint_f: 32.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.6,
            gust_kph: 18.7,
            uv: 5.0,
          },
          {
            time_epoch: 1645596000,
            time: "2022-02-23 08:00",
            temp_c: 17.7,
            temp_f: 63.9,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 4.5,
            wind_kph: 7.2,
            wind_degree: 179,
            wind_dir: "S",
            pressure_mb: 1012.0,
            pressure_in: 29.89,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 31,
            cloud: 3,
            feelslike_c: 17.7,
            feelslike_f: 63.9,
            windchill_c: 17.7,
            windchill_f: 63.9,
            heatindex_c: 17.7,
            heatindex_f: 63.9,
            dewpoint_c: 0.6,
            dewpoint_f: 33.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 7.6,
            gust_kph: 12.2,
            uv: 5.0,
          },
          {
            time_epoch: 1645599600,
            time: "2022-02-23 09:00",
            temp_c: 19.4,
            temp_f: 66.9,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 5.8,
            wind_kph: 9.4,
            wind_degree: 174,
            wind_dir: "S",
            pressure_mb: 1012.0,
            pressure_in: 29.88,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 28,
            cloud: 3,
            feelslike_c: 19.4,
            feelslike_f: 66.9,
            windchill_c: 19.4,
            windchill_f: 66.9,
            heatindex_c: 19.4,
            heatindex_f: 66.9,
            dewpoint_c: 0.4,
            dewpoint_f: 32.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 7.6,
            gust_kph: 12.2,
            uv: 5.0,
          },
          {
            time_epoch: 1645603200,
            time: "2022-02-23 10:00",
            temp_c: 21.2,
            temp_f: 70.2,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 9.6,
            wind_kph: 15.5,
            wind_degree: 139,
            wind_dir: "SE",
            pressure_mb: 1011.0,
            pressure_in: 29.85,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 25,
            cloud: 3,
            feelslike_c: 21.2,
            feelslike_f: 70.2,
            windchill_c: 21.2,
            windchill_f: 70.2,
            heatindex_c: 22.4,
            heatindex_f: 72.3,
            dewpoint_c: 0.2,
            dewpoint_f: 32.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.2,
            gust_kph: 18.0,
            uv: 6.0,
          },
          {
            time_epoch: 1645606800,
            time: "2022-02-23 11:00",
            temp_c: 23.0,
            temp_f: 73.4,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 9.6,
            wind_kph: 15.5,
            wind_degree: 187,
            wind_dir: "S",
            pressure_mb: 1011.0,
            pressure_in: 29.85,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 22,
            cloud: 5,
            feelslike_c: 22.8,
            feelslike_f: 73.0,
            windchill_c: 23.0,
            windchill_f: 73.4,
            heatindex_c: 22.8,
            heatindex_f: 73.0,
            dewpoint_c: 0.0,
            dewpoint_f: 32.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.2,
            gust_kph: 18.0,
            uv: 6.0,
          },
          {
            time_epoch: 1645610400,
            time: "2022-02-23 12:00",
            temp_c: 24.2,
            temp_f: 75.6,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 9.8,
            wind_kph: 15.8,
            wind_degree: 174,
            wind_dir: "S",
            pressure_mb: 1010.0,
            pressure_in: 29.81,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 20,
            cloud: 3,
            feelslike_c: 23.3,
            feelslike_f: 73.9,
            windchill_c: 24.2,
            windchill_f: 75.6,
            heatindex_c: 23.3,
            heatindex_f: 73.9,
            dewpoint_c: -0.2,
            dewpoint_f: 31.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.4,
            gust_kph: 18.4,
            uv: 6.0,
          },
          {
            time_epoch: 1645614000,
            time: "2022-02-23 13:00",
            temp_c: 26.6,
            temp_f: 79.9,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 12.1,
            wind_kph: 19.4,
            wind_degree: 169,
            wind_dir: "S",
            pressure_mb: 1008.0,
            pressure_in: 29.77,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 18,
            cloud: 8,
            feelslike_c: 24.9,
            feelslike_f: 76.8,
            windchill_c: 26.6,
            windchill_f: 79.9,
            heatindex_c: 24.9,
            heatindex_f: 76.8,
            dewpoint_c: 0.2,
            dewpoint_f: 32.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 13.9,
            gust_kph: 22.3,
            uv: 7.0,
          },
          {
            time_epoch: 1645617600,
            time: "2022-02-23 14:00",
            temp_c: 26.6,
            temp_f: 79.9,
            is_day: 1,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
              code: 1009,
            },
            wind_mph: 16.8,
            wind_kph: 27.0,
            wind_degree: 201,
            wind_dir: "SSW",
            pressure_mb: 1008.0,
            pressure_in: 29.77,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 16,
            cloud: 100,
            feelslike_c: 24.9,
            feelslike_f: 76.8,
            windchill_c: 26.6,
            windchill_f: 79.9,
            heatindex_c: 24.9,
            heatindex_f: 76.8,
            dewpoint_c: -1.5,
            dewpoint_f: 29.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 19.2,
            gust_kph: 31.0,
            uv: 6.0,
          },
          {
            time_epoch: 1645621200,
            time: "2022-02-23 15:00",
            temp_c: 26.3,
            temp_f: 79.3,
            is_day: 1,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
              code: 1009,
            },
            wind_mph: 15.7,
            wind_kph: 25.2,
            wind_degree: 195,
            wind_dir: "SSW",
            pressure_mb: 1007.0,
            pressure_in: 29.75,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 15,
            cloud: 100,
            feelslike_c: 24.7,
            feelslike_f: 76.5,
            windchill_c: 26.3,
            windchill_f: 79.3,
            heatindex_c: 24.7,
            heatindex_f: 76.5,
            dewpoint_c: -2.4,
            dewpoint_f: 27.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 18.1,
            gust_kph: 29.2,
            uv: 6.0,
          },
          {
            time_epoch: 1645624800,
            time: "2022-02-23 16:00",
            temp_c: 26.0,
            temp_f: 78.8,
            is_day: 1,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
              code: 1009,
            },
            wind_mph: 15.9,
            wind_kph: 25.6,
            wind_degree: 214,
            wind_dir: "SW",
            pressure_mb: 1007.0,
            pressure_in: 29.75,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 15,
            cloud: 100,
            feelslike_c: 24.5,
            feelslike_f: 76.1,
            windchill_c: 26.0,
            windchill_f: 78.8,
            heatindex_c: 24.5,
            heatindex_f: 76.1,
            dewpoint_c: -2.6,
            dewpoint_f: 27.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 18.6,
            gust_kph: 29.9,
            uv: 6.0,
          },
          {
            time_epoch: 1645628400,
            time: "2022-02-23 17:00",
            temp_c: 25.0,
            temp_f: 77.0,
            is_day: 1,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
              code: 1009,
            },
            wind_mph: 10.3,
            wind_kph: 16.6,
            wind_degree: 221,
            wind_dir: "SW",
            pressure_mb: 1007.0,
            pressure_in: 29.75,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 16,
            cloud: 100,
            feelslike_c: 23.8,
            feelslike_f: 74.8,
            windchill_c: 25.0,
            windchill_f: 77.0,
            heatindex_c: 23.8,
            heatindex_f: 74.8,
            dewpoint_c: -2.9,
            dewpoint_f: 26.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 14.5,
            gust_kph: 23.4,
            uv: 6.0,
          },
          {
            time_epoch: 1645632000,
            time: "2022-02-23 18:00",
            temp_c: 23.8,
            temp_f: 74.8,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 8.7,
            wind_kph: 14.0,
            wind_degree: 265,
            wind_dir: "W",
            pressure_mb: 1008.0,
            pressure_in: 29.75,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 20,
            cloud: 14,
            feelslike_c: 23.0,
            feelslike_f: 73.4,
            windchill_c: 23.8,
            windchill_f: 74.8,
            heatindex_c: 23.0,
            heatindex_f: 73.4,
            dewpoint_c: -0.6,
            dewpoint_f: 30.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 12.1,
            gust_kph: 19.4,
            uv: 1.0,
          },
          {
            time_epoch: 1645635600,
            time: "2022-02-23 19:00",
            temp_c: 20.6,
            temp_f: 69.1,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 23.3,
            wind_kph: 37.4,
            wind_degree: 299,
            wind_dir: "WNW",
            pressure_mb: 1009.0,
            pressure_in: 29.8,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 49,
            cloud: 3,
            feelslike_c: 20.6,
            feelslike_f: 69.1,
            windchill_c: 20.6,
            windchill_f: 69.1,
            heatindex_c: 20.6,
            heatindex_f: 69.1,
            dewpoint_c: 9.6,
            dewpoint_f: 49.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 26.8,
            gust_kph: 43.2,
            uv: 1.0,
          },
          {
            time_epoch: 1645639200,
            time: "2022-02-23 20:00",
            temp_c: 16.0,
            temp_f: 60.8,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 22.6,
            wind_kph: 36.4,
            wind_degree: 308,
            wind_dir: "NW",
            pressure_mb: 1010.0,
            pressure_in: 29.84,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 63,
            cloud: 3,
            feelslike_c: 16.0,
            feelslike_f: 60.8,
            windchill_c: 16.0,
            windchill_f: 60.8,
            heatindex_c: 16.0,
            heatindex_f: 60.8,
            dewpoint_c: 9.1,
            dewpoint_f: 48.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 26.6,
            gust_kph: 42.8,
            uv: 1.0,
          },
          {
            time_epoch: 1645642800,
            time: "2022-02-23 21:00",
            temp_c: 15.8,
            temp_f: 60.4,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 17.4,
            wind_kph: 28.1,
            wind_degree: 310,
            wind_dir: "NW",
            pressure_mb: 1011.0,
            pressure_in: 29.87,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 65,
            cloud: 3,
            feelslike_c: 15.8,
            feelslike_f: 60.4,
            windchill_c: 15.8,
            windchill_f: 60.4,
            heatindex_c: 15.8,
            heatindex_f: 60.4,
            dewpoint_c: 9.1,
            dewpoint_f: 48.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 20.1,
            gust_kph: 32.4,
            uv: 1.0,
          },
          {
            time_epoch: 1645646400,
            time: "2022-02-23 22:00",
            temp_c: 15.5,
            temp_f: 59.9,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 16.1,
            wind_kph: 25.9,
            wind_degree: 306,
            wind_dir: "NW",
            pressure_mb: 1012.0,
            pressure_in: 29.89,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 63,
            cloud: 3,
            feelslike_c: 15.5,
            feelslike_f: 59.9,
            windchill_c: 15.5,
            windchill_f: 59.9,
            heatindex_c: 15.5,
            heatindex_f: 59.9,
            dewpoint_c: 8.5,
            dewpoint_f: 47.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 18.6,
            gust_kph: 29.9,
            uv: 1.0,
          },
          {
            time_epoch: 1645650000,
            time: "2022-02-23 23:00",
            temp_c: 14.8,
            temp_f: 58.6,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 13.0,
            wind_kph: 20.9,
            wind_degree: 296,
            wind_dir: "WNW",
            pressure_mb: 1013.0,
            pressure_in: 29.9,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 62,
            cloud: 3,
            feelslike_c: 13.4,
            feelslike_f: 56.1,
            windchill_c: 13.4,
            windchill_f: 56.1,
            heatindex_c: 14.8,
            heatindex_f: 58.6,
            dewpoint_c: 7.7,
            dewpoint_f: 45.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 15.4,
            gust_kph: 24.8,
            uv: 1.0,
          },
        ],
      },
      {
        date: "2022-02-24",
        date_epoch: 1645660800,
        day: {
          maxtemp_c: 18.9,
          mintemp_c: 11.4,
          avgtemp_c: 15.1,
          maxwind_kph: 33.1,
          totalprecip_mm: 0.0,
          avgvis_km: 10.0,
          avghumidity: 47.0,
          daily_chance_of_rain: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Partly cloudy",
            icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
            code: 1003,
          },
        },
        astro: {
          sunrise: "06:26 AM",
          sunset: "05:51 PM",
          moonrise: "12:48 AM",
          moonset: "11:19 AM",
          moon_phase: "Last Quarter",
          moon_illumination: "32",
        },
        hour: [
          {
            time_epoch: 1645653600,
            time: "2022-02-24 00:00",
            temp_c: 14.0,
            temp_f: 57.2,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 10.5,
            wind_kph: 16.9,
            wind_degree: 278,
            wind_dir: "W",
            pressure_mb: 1013.0,
            pressure_in: 29.91,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 57,
            cloud: 2,
            feelslike_c: 12.7,
            feelslike_f: 54.9,
            windchill_c: 12.7,
            windchill_f: 54.9,
            heatindex_c: 14.0,
            heatindex_f: 57.2,
            dewpoint_c: 5.6,
            dewpoint_f: 42.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 14.1,
            gust_kph: 22.7,
            uv: 1.0,
          },
          {
            time_epoch: 1645657200,
            time: "2022-02-24 01:00",
            temp_c: 13.3,
            temp_f: 55.9,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 8.9,
            wind_kph: 14.4,
            wind_degree: 262,
            wind_dir: "W",
            pressure_mb: 1013.0,
            pressure_in: 29.91,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 52,
            cloud: 0,
            feelslike_c: 12.0,
            feelslike_f: 53.6,
            windchill_c: 12.0,
            windchill_f: 53.6,
            heatindex_c: 13.3,
            heatindex_f: 55.9,
            dewpoint_c: 3.7,
            dewpoint_f: 38.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 13.2,
            gust_kph: 21.2,
            uv: 1.0,
          },
          {
            time_epoch: 1645660800,
            time: "2022-02-24 02:00",
            temp_c: 12.6,
            temp_f: 54.7,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 8.1,
            wind_kph: 13.0,
            wind_degree: 247,
            wind_dir: "WSW",
            pressure_mb: 1013.0,
            pressure_in: 29.91,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 51,
            cloud: 0,
            feelslike_c: 11.3,
            feelslike_f: 52.3,
            windchill_c: 11.3,
            windchill_f: 52.3,
            heatindex_c: 12.6,
            heatindex_f: 54.7,
            dewpoint_c: 2.9,
            dewpoint_f: 37.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 13.0,
            gust_kph: 20.9,
            uv: 1.0,
          },
          {
            time_epoch: 1645664400,
            time: "2022-02-24 03:00",
            temp_c: 12.3,
            temp_f: 54.1,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 7.8,
            wind_kph: 12.6,
            wind_degree: 228,
            wind_dir: "SW",
            pressure_mb: 1012.0,
            pressure_in: 29.9,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 51,
            cloud: 0,
            feelslike_c: 11.0,
            feelslike_f: 51.8,
            windchill_c: 11.0,
            windchill_f: 51.8,
            heatindex_c: 12.3,
            heatindex_f: 54.1,
            dewpoint_c: 2.6,
            dewpoint_f: 36.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 13.0,
            gust_kph: 20.9,
            uv: 1.0,
          },
          {
            time_epoch: 1645668000,
            time: "2022-02-24 04:00",
            temp_c: 12.1,
            temp_f: 53.8,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 8.5,
            wind_kph: 13.7,
            wind_degree: 213,
            wind_dir: "SSW",
            pressure_mb: 1012.0,
            pressure_in: 29.89,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 52,
            cloud: 0,
            feelslike_c: 10.7,
            feelslike_f: 51.3,
            windchill_c: 10.7,
            windchill_f: 51.3,
            heatindex_c: 12.1,
            heatindex_f: 53.8,
            dewpoint_c: 2.4,
            dewpoint_f: 36.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 14.3,
            gust_kph: 23.0,
            uv: 1.0,
          },
          {
            time_epoch: 1645671600,
            time: "2022-02-24 05:00",
            temp_c: 11.8,
            temp_f: 53.2,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 10.1,
            wind_kph: 16.2,
            wind_degree: 206,
            wind_dir: "SSW",
            pressure_mb: 1012.0,
            pressure_in: 29.89,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 53,
            cloud: 3,
            feelslike_c: 10.0,
            feelslike_f: 50.0,
            windchill_c: 10.0,
            windchill_f: 50.0,
            heatindex_c: 11.8,
            heatindex_f: 53.2,
            dewpoint_c: 2.5,
            dewpoint_f: 36.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 17.2,
            gust_kph: 27.7,
            uv: 1.0,
          },
          {
            time_epoch: 1645675200,
            time: "2022-02-24 06:00",
            temp_c: 11.4,
            temp_f: 52.5,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 11.2,
            wind_kph: 18.0,
            wind_degree: 204,
            wind_dir: "SSW",
            pressure_mb: 1013.0,
            pressure_in: 29.9,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 55,
            cloud: 6,
            feelslike_c: 9.3,
            feelslike_f: 48.7,
            windchill_c: 9.3,
            windchill_f: 48.7,
            heatindex_c: 11.4,
            heatindex_f: 52.5,
            dewpoint_c: 2.8,
            dewpoint_f: 37.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 19.5,
            gust_kph: 31.3,
            uv: 1.0,
          },
          {
            time_epoch: 1645678800,
            time: "2022-02-24 07:00",
            temp_c: 11.5,
            temp_f: 52.7,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 11.9,
            wind_kph: 19.1,
            wind_degree: 199,
            wind_dir: "SSW",
            pressure_mb: 1013.0,
            pressure_in: 29.91,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 55,
            cloud: 16,
            feelslike_c: 9.3,
            feelslike_f: 48.7,
            windchill_c: 9.3,
            windchill_f: 48.7,
            heatindex_c: 11.5,
            heatindex_f: 52.7,
            dewpoint_c: 2.9,
            dewpoint_f: 37.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 19.7,
            gust_kph: 31.7,
            uv: 4.0,
          },
          {
            time_epoch: 1645682400,
            time: "2022-02-24 08:00",
            temp_c: 13.1,
            temp_f: 55.6,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 13.4,
            wind_kph: 21.6,
            wind_degree: 206,
            wind_dir: "SSW",
            pressure_mb: 1013.0,
            pressure_in: 29.92,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 50,
            cloud: 28,
            feelslike_c: 11.2,
            feelslike_f: 52.2,
            windchill_c: 11.2,
            windchill_f: 52.2,
            heatindex_c: 13.1,
            heatindex_f: 55.6,
            dewpoint_c: 3.0,
            dewpoint_f: 37.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 17.4,
            gust_kph: 28.1,
            uv: 4.0,
          },
          {
            time_epoch: 1645686000,
            time: "2022-02-24 09:00",
            temp_c: 14.8,
            temp_f: 58.6,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 14.8,
            wind_kph: 23.8,
            wind_degree: 214,
            wind_dir: "SW",
            pressure_mb: 1013.0,
            pressure_in: 29.92,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 43,
            cloud: 28,
            feelslike_c: 13.2,
            feelslike_f: 55.8,
            windchill_c: 13.2,
            windchill_f: 55.8,
            heatindex_c: 14.8,
            heatindex_f: 58.6,
            dewpoint_c: 2.4,
            dewpoint_f: 36.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 17.0,
            gust_kph: 27.4,
            uv: 4.0,
          },
          {
            time_epoch: 1645689600,
            time: "2022-02-24 10:00",
            temp_c: 16.1,
            temp_f: 61.0,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 15.0,
            wind_kph: 24.1,
            wind_degree: 216,
            wind_dir: "SW",
            pressure_mb: 1013.0,
            pressure_in: 29.92,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 40,
            cloud: 22,
            feelslike_c: 16.1,
            feelslike_f: 61.0,
            windchill_c: 16.1,
            windchill_f: 61.0,
            heatindex_c: 16.1,
            heatindex_f: 61.0,
            dewpoint_c: 2.5,
            dewpoint_f: 36.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 17.2,
            gust_kph: 27.7,
            uv: 5.0,
          },
          {
            time_epoch: 1645693200,
            time: "2022-02-24 11:00",
            temp_c: 17.7,
            temp_f: 63.9,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 16.6,
            wind_kph: 26.6,
            wind_degree: 225,
            wind_dir: "SW",
            pressure_mb: 1013.0,
            pressure_in: 29.92,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 38,
            cloud: 45,
            feelslike_c: 17.7,
            feelslike_f: 63.9,
            windchill_c: 17.7,
            windchill_f: 63.9,
            heatindex_c: 17.7,
            heatindex_f: 63.9,
            dewpoint_c: 3.4,
            dewpoint_f: 38.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 19.0,
            gust_kph: 30.6,
            uv: 5.0,
          },
          {
            time_epoch: 1645696800,
            time: "2022-02-24 12:00",
            temp_c: 18.5,
            temp_f: 65.3,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 18.8,
            wind_kph: 30.2,
            wind_degree: 225,
            wind_dir: "SW",
            pressure_mb: 1013.0,
            pressure_in: 29.9,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 36,
            cloud: 44,
            feelslike_c: 18.5,
            feelslike_f: 65.3,
            windchill_c: 18.5,
            windchill_f: 65.3,
            heatindex_c: 18.5,
            heatindex_f: 65.3,
            dewpoint_c: 3.1,
            dewpoint_f: 37.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 21.7,
            gust_kph: 34.9,
            uv: 5.0,
          },
          {
            time_epoch: 1645700400,
            time: "2022-02-24 13:00",
            temp_c: 18.9,
            temp_f: 66.0,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 20.6,
            wind_kph: 33.1,
            wind_degree: 228,
            wind_dir: "SW",
            pressure_mb: 1012.0,
            pressure_in: 29.88,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 34,
            cloud: 46,
            feelslike_c: 18.9,
            feelslike_f: 66.0,
            windchill_c: 18.9,
            windchill_f: 66.0,
            heatindex_c: 18.9,
            heatindex_f: 66.0,
            dewpoint_c: 2.8,
            dewpoint_f: 37.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 23.7,
            gust_kph: 38.2,
            uv: 5.0,
          },
          {
            time_epoch: 1645704000,
            time: "2022-02-24 14:00",
            temp_c: 18.9,
            temp_f: 66.0,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 20.4,
            wind_kph: 32.8,
            wind_degree: 236,
            wind_dir: "WSW",
            pressure_mb: 1011.0,
            pressure_in: 29.86,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 34,
            cloud: 44,
            feelslike_c: 18.9,
            feelslike_f: 66.0,
            windchill_c: 18.9,
            windchill_f: 66.0,
            heatindex_c: 18.9,
            heatindex_f: 66.0,
            dewpoint_c: 2.9,
            dewpoint_f: 37.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 23.5,
            gust_kph: 37.8,
            uv: 5.0,
          },
          {
            time_epoch: 1645707600,
            time: "2022-02-24 15:00",
            temp_c: 18.0,
            temp_f: 64.4,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 20.4,
            wind_kph: 32.8,
            wind_degree: 252,
            wind_dir: "WSW",
            pressure_mb: 1012.0,
            pressure_in: 29.87,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 38,
            cloud: 60,
            feelslike_c: 18.0,
            feelslike_f: 64.4,
            windchill_c: 18.0,
            windchill_f: 64.4,
            heatindex_c: 18.0,
            heatindex_f: 64.4,
            dewpoint_c: 3.5,
            dewpoint_f: 38.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 23.5,
            gust_kph: 37.8,
            uv: 5.0,
          },
          {
            time_epoch: 1645711200,
            time: "2022-02-24 16:00",
            temp_c: 17.6,
            temp_f: 63.7,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 19.9,
            wind_kph: 32.0,
            wind_degree: 256,
            wind_dir: "WSW",
            pressure_mb: 1012.0,
            pressure_in: 29.88,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 41,
            cloud: 56,
            feelslike_c: 17.6,
            feelslike_f: 63.7,
            windchill_c: 17.6,
            windchill_f: 63.7,
            heatindex_c: 17.6,
            heatindex_f: 63.7,
            dewpoint_c: 4.1,
            dewpoint_f: 39.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 22.8,
            gust_kph: 36.7,
            uv: 5.0,
          },
          {
            time_epoch: 1645714800,
            time: "2022-02-24 17:00",
            temp_c: 17.6,
            temp_f: 63.7,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 16.3,
            wind_kph: 26.3,
            wind_degree: 256,
            wind_dir: "WSW",
            pressure_mb: 1012.0,
            pressure_in: 29.89,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 43,
            cloud: 27,
            feelslike_c: 17.6,
            feelslike_f: 63.7,
            windchill_c: 17.6,
            windchill_f: 63.7,
            heatindex_c: 17.6,
            heatindex_f: 63.7,
            dewpoint_c: 4.8,
            dewpoint_f: 40.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 18.8,
            gust_kph: 30.2,
            uv: 5.0,
          },
          {
            time_epoch: 1645718400,
            time: "2022-02-24 18:00",
            temp_c: 17.0,
            temp_f: 62.6,
            is_day: 0,
            condition: {
              text: "Cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/119.png",
              code: 1006,
            },
            wind_mph: 13.4,
            wind_kph: 21.6,
            wind_degree: 249,
            wind_dir: "WSW",
            pressure_mb: 1013.0,
            pressure_in: 29.9,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 41,
            cloud: 68,
            feelslike_c: 17.0,
            feelslike_f: 62.6,
            windchill_c: 17.0,
            windchill_f: 62.6,
            heatindex_c: 17.0,
            heatindex_f: 62.6,
            dewpoint_c: 3.8,
            dewpoint_f: 38.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 15.4,
            gust_kph: 24.8,
            uv: 1.0,
          },
          {
            time_epoch: 1645722000,
            time: "2022-02-24 19:00",
            temp_c: 17.2,
            temp_f: 63.0,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 13.9,
            wind_kph: 22.3,
            wind_degree: 264,
            wind_dir: "W",
            pressure_mb: 1013.0,
            pressure_in: 29.93,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 43,
            cloud: 45,
            feelslike_c: 17.2,
            feelslike_f: 63.0,
            windchill_c: 17.2,
            windchill_f: 63.0,
            heatindex_c: 17.2,
            heatindex_f: 63.0,
            dewpoint_c: 4.4,
            dewpoint_f: 39.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 15.9,
            gust_kph: 25.6,
            uv: 1.0,
          },
          {
            time_epoch: 1645725600,
            time: "2022-02-24 20:00",
            temp_c: 15.8,
            temp_f: 60.4,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 13.9,
            wind_kph: 22.3,
            wind_degree: 249,
            wind_dir: "WSW",
            pressure_mb: 1014.0,
            pressure_in: 29.94,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 45,
            cloud: 28,
            feelslike_c: 15.8,
            feelslike_f: 60.4,
            windchill_c: 15.8,
            windchill_f: 60.4,
            heatindex_c: 15.8,
            heatindex_f: 60.4,
            dewpoint_c: 3.9,
            dewpoint_f: 39.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 18.1,
            gust_kph: 29.2,
            uv: 1.0,
          },
          {
            time_epoch: 1645729200,
            time: "2022-02-24 21:00",
            temp_c: 14.4,
            temp_f: 57.9,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 16.1,
            wind_kph: 25.9,
            wind_degree: 240,
            wind_dir: "WSW",
            pressure_mb: 1014.0,
            pressure_in: 29.94,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 55,
            cloud: 16,
            feelslike_c: 12.5,
            feelslike_f: 54.5,
            windchill_c: 12.5,
            windchill_f: 54.5,
            heatindex_c: 14.4,
            heatindex_f: 57.9,
            dewpoint_c: 5.4,
            dewpoint_f: 41.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 21.3,
            gust_kph: 34.2,
            uv: 1.0,
          },
          {
            time_epoch: 1645732800,
            time: "2022-02-24 22:00",
            temp_c: 13.7,
            temp_f: 56.7,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 13.6,
            wind_kph: 22.0,
            wind_degree: 238,
            wind_dir: "WSW",
            pressure_mb: 1014.0,
            pressure_in: 29.94,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 57,
            cloud: 15,
            feelslike_c: 11.9,
            feelslike_f: 53.4,
            windchill_c: 11.9,
            windchill_f: 53.4,
            heatindex_c: 13.7,
            heatindex_f: 56.7,
            dewpoint_c: 5.4,
            dewpoint_f: 41.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 19.9,
            gust_kph: 32.0,
            uv: 1.0,
          },
          {
            time_epoch: 1645736400,
            time: "2022-02-24 23:00",
            temp_c: 13.5,
            temp_f: 56.3,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 13.0,
            wind_kph: 20.9,
            wind_degree: 234,
            wind_dir: "SW",
            pressure_mb: 1014.0,
            pressure_in: 29.95,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 59,
            cloud: 20,
            feelslike_c: 11.7,
            feelslike_f: 53.1,
            windchill_c: 11.7,
            windchill_f: 53.1,
            heatindex_c: 13.5,
            heatindex_f: 56.3,
            dewpoint_c: 5.7,
            dewpoint_f: 42.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 18.8,
            gust_kph: 30.2,
            uv: 1.0,
          },
        ],
      },
      {
        date: "2022-02-25",
        date_epoch: 1645747200,
        day: {
          maxtemp_c: 18.3,
          mintemp_c: 11.9,
          avgtemp_c: 14.3,
          maxwind_kph: 33.5,
          totalprecip_mm: 0.5,
          avgvis_km: 10.0,
          avghumidity: 58.0,
          daily_chance_of_rain: 72,
          daily_chance_of_snow: 0,
          condition: {
            text: "Patchy rain possible",
            icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
            code: 1063,
          },
        },
        astro: {
          sunrise: "06:25 AM",
          sunset: "05:52 PM",
          moonrise: "01:56 AM",
          moonset: "12:11 PM",
          moon_phase: "Last Quarter",
          moon_illumination: "24",
        },
        hour: [
          {
            time_epoch: 1645740000,
            time: "2022-02-25 00:00",
            temp_c: 12.7,
            temp_f: 54.9,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 12.1,
            wind_kph: 19.4,
            wind_degree: 232,
            wind_dir: "SW",
            pressure_mb: 1014.0,
            pressure_in: 29.94,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 62,
            cloud: 9,
            feelslike_c: 10.8,
            feelslike_f: 51.4,
            windchill_c: 10.8,
            windchill_f: 51.4,
            heatindex_c: 12.7,
            heatindex_f: 54.9,
            dewpoint_c: 5.6,
            dewpoint_f: 42.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 18.8,
            gust_kph: 30.2,
            uv: 1.0,
          },
          {
            time_epoch: 1645743600,
            time: "2022-02-25 01:00",
            temp_c: 12.4,
            temp_f: 54.3,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 13.0,
            wind_kph: 20.9,
            wind_degree: 225,
            wind_dir: "SW",
            pressure_mb: 1014.0,
            pressure_in: 29.94,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 65,
            cloud: 11,
            feelslike_c: 10.3,
            feelslike_f: 50.5,
            windchill_c: 10.3,
            windchill_f: 50.5,
            heatindex_c: 12.4,
            heatindex_f: 54.3,
            dewpoint_c: 5.9,
            dewpoint_f: 42.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 19.7,
            gust_kph: 31.7,
            uv: 1.0,
          },
          {
            time_epoch: 1645747200,
            time: "2022-02-25 02:00",
            temp_c: 12.1,
            temp_f: 53.8,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 13.0,
            wind_kph: 20.9,
            wind_degree: 224,
            wind_dir: "SW",
            pressure_mb: 1014.0,
            pressure_in: 29.94,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 67,
            cloud: 52,
            feelslike_c: 9.9,
            feelslike_f: 49.8,
            windchill_c: 9.9,
            windchill_f: 49.8,
            heatindex_c: 12.1,
            heatindex_f: 53.8,
            dewpoint_c: 6.2,
            dewpoint_f: 43.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 19.7,
            gust_kph: 31.7,
            uv: 1.0,
          },
          {
            time_epoch: 1645750800,
            time: "2022-02-25 03:00",
            temp_c: 12.0,
            temp_f: 53.6,
            is_day: 0,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
              code: 1009,
            },
            wind_mph: 13.4,
            wind_kph: 21.6,
            wind_degree: 230,
            wind_dir: "SW",
            pressure_mb: 1014.0,
            pressure_in: 29.94,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 69,
            cloud: 90,
            feelslike_c: 9.8,
            feelslike_f: 49.6,
            windchill_c: 9.8,
            windchill_f: 49.6,
            heatindex_c: 12.0,
            heatindex_f: 53.6,
            dewpoint_c: 6.5,
            dewpoint_f: 43.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 19.9,
            gust_kph: 32.0,
            uv: 1.0,
          },
          {
            time_epoch: 1645754400,
            time: "2022-02-25 04:00",
            temp_c: 12.0,
            temp_f: 53.6,
            is_day: 0,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
              code: 1009,
            },
            wind_mph: 15.0,
            wind_kph: 24.1,
            wind_degree: 243,
            wind_dir: "WSW",
            pressure_mb: 1014.0,
            pressure_in: 29.94,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 72,
            cloud: 90,
            feelslike_c: 9.6,
            feelslike_f: 49.3,
            windchill_c: 9.6,
            windchill_f: 49.3,
            heatindex_c: 12.0,
            heatindex_f: 53.6,
            dewpoint_c: 7.1,
            dewpoint_f: 44.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 21.0,
            gust_kph: 33.8,
            uv: 1.0,
          },
          {
            time_epoch: 1645758000,
            time: "2022-02-25 05:00",
            temp_c: 12.0,
            temp_f: 53.6,
            is_day: 0,
            condition: {
              text: "Light rain shower",
              icon: "//cdn.weatherapi.com/weather/64x64/night/353.png",
              code: 1240,
            },
            wind_mph: 16.1,
            wind_kph: 25.9,
            wind_degree: 247,
            wind_dir: "WSW",
            pressure_mb: 1015.0,
            pressure_in: 29.96,
            precip_mm: 0.3,
            precip_in: 0.01,
            humidity: 75,
            cloud: 56,
            feelslike_c: 9.4,
            feelslike_f: 48.9,
            windchill_c: 9.4,
            windchill_f: 48.9,
            heatindex_c: 12.0,
            heatindex_f: 53.6,
            dewpoint_c: 7.7,
            dewpoint_f: 45.9,
            will_it_rain: 1,
            chance_of_rain: 72,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 23.5,
            gust_kph: 37.8,
            uv: 1.0,
          },
          {
            time_epoch: 1645761600,
            time: "2022-02-25 06:00",
            temp_c: 11.9,
            temp_f: 53.4,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 18.6,
            wind_kph: 29.9,
            wind_degree: 265,
            wind_dir: "W",
            pressure_mb: 1015.0,
            pressure_in: 29.98,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 77,
            cloud: 44,
            feelslike_c: 9.1,
            feelslike_f: 48.4,
            windchill_c: 9.1,
            windchill_f: 48.4,
            heatindex_c: 11.9,
            heatindex_f: 53.4,
            dewpoint_c: 8.0,
            dewpoint_f: 46.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 26.6,
            gust_kph: 42.8,
            uv: 1.0,
          },
          {
            time_epoch: 1645765200,
            time: "2022-02-25 07:00",
            temp_c: 11.9,
            temp_f: 53.4,
            is_day: 1,
            condition: {
              text: "Patchy rain possible",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 15.4,
            wind_kph: 24.8,
            wind_degree: 279,
            wind_dir: "W",
            pressure_mb: 1016.0,
            pressure_in: 30.0,
            precip_mm: 0.2,
            precip_in: 0.01,
            humidity: 75,
            cloud: 84,
            feelslike_c: 9.4,
            feelslike_f: 48.9,
            windchill_c: 9.4,
            windchill_f: 48.9,
            heatindex_c: 11.9,
            heatindex_f: 53.4,
            dewpoint_c: 7.5,
            dewpoint_f: 45.5,
            will_it_rain: 0,
            chance_of_rain: 64,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9.0,
            vis_miles: 5.0,
            gust_mph: 21.0,
            gust_kph: 33.8,
            uv: 3.0,
          },
          {
            time_epoch: 1645768800,
            time: "2022-02-25 08:00",
            temp_c: 12.7,
            temp_f: 54.9,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 17.9,
            wind_kph: 28.8,
            wind_degree: 274,
            wind_dir: "W",
            pressure_mb: 1017.0,
            pressure_in: 30.02,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 68,
            cloud: 48,
            feelslike_c: 10.2,
            feelslike_f: 50.4,
            windchill_c: 10.2,
            windchill_f: 50.4,
            heatindex_c: 12.7,
            heatindex_f: 54.9,
            dewpoint_c: 6.9,
            dewpoint_f: 44.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 22.6,
            gust_kph: 36.4,
            uv: 4.0,
          },
          {
            time_epoch: 1645772400,
            time: "2022-02-25 09:00",
            temp_c: 13.6,
            temp_f: 56.5,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 19.5,
            wind_kph: 31.3,
            wind_degree: 272,
            wind_dir: "W",
            pressure_mb: 1017.0,
            pressure_in: 30.03,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 57,
            cloud: 30,
            feelslike_c: 11.2,
            feelslike_f: 52.2,
            windchill_c: 11.2,
            windchill_f: 52.2,
            heatindex_c: 13.6,
            heatindex_f: 56.5,
            dewpoint_c: 5.3,
            dewpoint_f: 41.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 22.4,
            gust_kph: 36.0,
            uv: 4.0,
          },
          {
            time_epoch: 1645776000,
            time: "2022-02-25 10:00",
            temp_c: 14.9,
            temp_f: 58.8,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 19.7,
            wind_kph: 31.7,
            wind_degree: 278,
            wind_dir: "W",
            pressure_mb: 1017.0,
            pressure_in: 30.04,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 50,
            cloud: 3,
            feelslike_c: 12.9,
            feelslike_f: 55.2,
            windchill_c: 12.9,
            windchill_f: 55.2,
            heatindex_c: 14.9,
            heatindex_f: 58.8,
            dewpoint_c: 4.5,
            dewpoint_f: 40.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 22.6,
            gust_kph: 36.4,
            uv: 4.0,
          },
          {
            time_epoch: 1645779600,
            time: "2022-02-25 11:00",
            temp_c: 16.5,
            temp_f: 61.7,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 20.1,
            wind_kph: 32.4,
            wind_degree: 279,
            wind_dir: "W",
            pressure_mb: 1017.0,
            pressure_in: 30.04,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 45,
            cloud: 46,
            feelslike_c: 16.5,
            feelslike_f: 61.7,
            windchill_c: 16.5,
            windchill_f: 61.7,
            heatindex_c: 16.5,
            heatindex_f: 61.7,
            dewpoint_c: 4.5,
            dewpoint_f: 40.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 23.0,
            gust_kph: 37.1,
            uv: 5.0,
          },
          {
            time_epoch: 1645783200,
            time: "2022-02-25 12:00",
            temp_c: 17.9,
            temp_f: 64.2,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 19.9,
            wind_kph: 32.0,
            wind_degree: 282,
            wind_dir: "WNW",
            pressure_mb: 1017.0,
            pressure_in: 30.03,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 39,
            cloud: 31,
            feelslike_c: 17.9,
            feelslike_f: 64.2,
            windchill_c: 17.9,
            windchill_f: 64.2,
            heatindex_c: 17.9,
            heatindex_f: 64.2,
            dewpoint_c: 3.9,
            dewpoint_f: 39.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 22.8,
            gust_kph: 36.7,
            uv: 5.0,
          },
          {
            time_epoch: 1645786800,
            time: "2022-02-25 13:00",
            temp_c: 17.9,
            temp_f: 64.2,
            is_day: 1,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
              code: 1009,
            },
            wind_mph: 20.6,
            wind_kph: 33.1,
            wind_degree: 290,
            wind_dir: "WNW",
            pressure_mb: 1017.0,
            pressure_in: 30.02,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 39,
            cloud: 100,
            feelslike_c: 17.9,
            feelslike_f: 64.2,
            windchill_c: 17.9,
            windchill_f: 64.2,
            heatindex_c: 17.9,
            heatindex_f: 64.2,
            dewpoint_c: 3.7,
            dewpoint_f: 38.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 23.7,
            gust_kph: 38.2,
            uv: 4.0,
          },
          {
            time_epoch: 1645790400,
            time: "2022-02-25 14:00",
            temp_c: 17.3,
            temp_f: 63.1,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 19.2,
            wind_kph: 31.0,
            wind_degree: 295,
            wind_dir: "WNW",
            pressure_mb: 1017.0,
            pressure_in: 30.02,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 40,
            cloud: 62,
            feelslike_c: 17.3,
            feelslike_f: 63.1,
            windchill_c: 17.3,
            windchill_f: 63.1,
            heatindex_c: 17.3,
            heatindex_f: 63.1,
            dewpoint_c: 3.6,
            dewpoint_f: 38.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 22.1,
            gust_kph: 35.6,
            uv: 5.0,
          },
          {
            time_epoch: 1645794000,
            time: "2022-02-25 15:00",
            temp_c: 18.3,
            temp_f: 64.9,
            is_day: 1,
            condition: {
              text: "Cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
              code: 1006,
            },
            wind_mph: 18.6,
            wind_kph: 29.9,
            wind_degree: 292,
            wind_dir: "WNW",
            pressure_mb: 1017.0,
            pressure_in: 30.02,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 37,
            cloud: 73,
            feelslike_c: 18.3,
            feelslike_f: 64.9,
            windchill_c: 18.3,
            windchill_f: 64.9,
            heatindex_c: 18.3,
            heatindex_f: 64.9,
            dewpoint_c: 3.5,
            dewpoint_f: 38.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 21.5,
            gust_kph: 34.6,
            uv: 4.0,
          },
          {
            time_epoch: 1645797600,
            time: "2022-02-25 16:00",
            temp_c: 17.0,
            temp_f: 62.6,
            is_day: 1,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
              code: 1009,
            },
            wind_mph: 20.8,
            wind_kph: 33.5,
            wind_degree: 306,
            wind_dir: "NW",
            pressure_mb: 1017.0,
            pressure_in: 30.03,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 48,
            cloud: 100,
            feelslike_c: 17.0,
            feelslike_f: 62.6,
            windchill_c: 17.0,
            windchill_f: 62.6,
            heatindex_c: 17.0,
            heatindex_f: 62.6,
            dewpoint_c: 5.9,
            dewpoint_f: 42.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 23.9,
            gust_kph: 38.5,
            uv: 4.0,
          },
          {
            time_epoch: 1645801200,
            time: "2022-02-25 17:00",
            temp_c: 17.2,
            temp_f: 63.0,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 18.3,
            wind_kph: 29.5,
            wind_degree: 300,
            wind_dir: "WNW",
            pressure_mb: 1018.0,
            pressure_in: 30.05,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 46,
            cloud: 56,
            feelslike_c: 17.2,
            feelslike_f: 63.0,
            windchill_c: 17.2,
            windchill_f: 63.0,
            heatindex_c: 17.2,
            heatindex_f: 63.0,
            dewpoint_c: 5.5,
            dewpoint_f: 41.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 21.0,
            gust_kph: 33.8,
            uv: 5.0,
          },
          {
            time_epoch: 1645804800,
            time: "2022-02-25 18:00",
            temp_c: 15.7,
            temp_f: 60.3,
            is_day: 0,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
              code: 1009,
            },
            wind_mph: 16.8,
            wind_kph: 27.0,
            wind_degree: 317,
            wind_dir: "NW",
            pressure_mb: 1018.0,
            pressure_in: 30.07,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 58,
            cloud: 100,
            feelslike_c: 15.7,
            feelslike_f: 60.3,
            windchill_c: 15.7,
            windchill_f: 60.3,
            heatindex_c: 15.7,
            heatindex_f: 60.3,
            dewpoint_c: 7.5,
            dewpoint_f: 45.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 19.2,
            gust_kph: 31.0,
            uv: 1.0,
          },
          {
            time_epoch: 1645808400,
            time: "2022-02-25 19:00",
            temp_c: 16.3,
            temp_f: 61.3,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 13.9,
            wind_kph: 22.3,
            wind_degree: 319,
            wind_dir: "NW",
            pressure_mb: 1019.0,
            pressure_in: 30.09,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 64,
            cloud: 13,
            feelslike_c: 16.3,
            feelslike_f: 61.3,
            windchill_c: 16.3,
            windchill_f: 61.3,
            heatindex_c: 16.3,
            heatindex_f: 61.3,
            dewpoint_c: 9.4,
            dewpoint_f: 48.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 15.9,
            gust_kph: 25.6,
            uv: 1.0,
          },
          {
            time_epoch: 1645812000,
            time: "2022-02-25 20:00",
            temp_c: 13.7,
            temp_f: 56.7,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 11.9,
            wind_kph: 19.1,
            wind_degree: 311,
            wind_dir: "NW",
            pressure_mb: 1020.0,
            pressure_in: 30.11,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 64,
            cloud: 4,
            feelslike_c: 12.1,
            feelslike_f: 53.8,
            windchill_c: 12.1,
            windchill_f: 53.8,
            heatindex_c: 13.7,
            heatindex_f: 56.7,
            dewpoint_c: 6.9,
            dewpoint_f: 44.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 16.3,
            gust_kph: 26.3,
            uv: 1.0,
          },
          {
            time_epoch: 1645815600,
            time: "2022-02-25 21:00",
            temp_c: 13.1,
            temp_f: 55.6,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 9.8,
            wind_kph: 15.8,
            wind_degree: 301,
            wind_dir: "WNW",
            pressure_mb: 1020.0,
            pressure_in: 30.12,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 62,
            cloud: 2,
            feelslike_c: 11.7,
            feelslike_f: 53.1,
            windchill_c: 11.7,
            windchill_f: 53.1,
            heatindex_c: 13.1,
            heatindex_f: 55.6,
            dewpoint_c: 6.0,
            dewpoint_f: 42.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 14.5,
            gust_kph: 23.4,
            uv: 1.0,
          },
          {
            time_epoch: 1645819200,
            time: "2022-02-25 22:00",
            temp_c: 12.6,
            temp_f: 54.7,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 8.7,
            wind_kph: 14.0,
            wind_degree: 288,
            wind_dir: "WNW",
            pressure_mb: 1020.0,
            pressure_in: 30.13,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 61,
            cloud: 0,
            feelslike_c: 11.2,
            feelslike_f: 52.2,
            windchill_c: 11.2,
            windchill_f: 52.2,
            heatindex_c: 12.6,
            heatindex_f: 54.7,
            dewpoint_c: 5.3,
            dewpoint_f: 41.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 13.4,
            gust_kph: 21.6,
            uv: 1.0,
          },
          {
            time_epoch: 1645822800,
            time: "2022-02-25 23:00",
            temp_c: 12.0,
            temp_f: 53.6,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 8.9,
            wind_kph: 14.4,
            wind_degree: 289,
            wind_dir: "WNW",
            pressure_mb: 1020.0,
            pressure_in: 30.12,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 63,
            cloud: 0,
            feelslike_c: 10.4,
            feelslike_f: 50.7,
            windchill_c: 10.4,
            windchill_f: 50.7,
            heatindex_c: 12.0,
            heatindex_f: 53.6,
            dewpoint_c: 5.2,
            dewpoint_f: 41.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 14.3,
            gust_kph: 23.0,
            uv: 1.0,
          },
        ],
      },
    ],
  },
};

export default response;